# Aliases
alias migrate="rake db:migrate db:test:prepare"
alias remigrate="rake db:migrate && rake db:migrate:redo && rake db:schema:dump db:test:prepare"
alias g="git"
alias gst="g status"
alias tu="ruby_test unit"
alias tf="ruby_test functional"
alias s="bundle exec rspec"
alias cuc="bundle exec cucumber"
alias sm="ruby_spec models"
alias sc="ruby_spec controllers"
alias ti="ruby_test integration"
alias gi="gem install"
alias giv="gem install -v"
alias gci="git pull --rebase && rake && git push"
alias tlf="tail -f"
alias eydeploy="ey deploy -e \${\$(pwd):t}_staging"
alias eypending="git log \$(ey ssh \"cat /data/\${\$(pwd):t}/current/REVISION\" -e \${\$(pwd):t}_production)..origin/master"
alias hdeploy="git push staging master && heroku rake db:migrate --app \${\$(pwd):t}-staging"
alias hconsole="heroku console --app \${\$(pwd):t}-staging"
alias b="bundle"
alias be="bundle exec"
alias freshstart="rake db:drop && rake db:create && rake db:migrate && rake db:seed && rake db:test:prepare"
alias nombom='npm cache clear && bower cache clean && rm -rf node_modules bower_components && npm install && bower install'
alias nimbim="npm install && bower install"
alias stree='open -a SourceTree'
alias vim="/usr/local/bin/vim"

# Ember.js
alias ets="ember test --server --launch=false"
alias es="ember s"
alias esh="IS_HYNDE_ENABLED=false ember s"

# Downloading
alias ydl="youtube-dl -x --audio-format wav --audio-quality 0"

alias c="cd ~/code/"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set iTerm title
precmd() {
  # sets the tab title to current dir
  echo -ne "\e]1;${PWD##*/}\a"
}